# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: inprocess-usdc-comments-indexer
contracts:
  - name: ERC20Minter
    handler: src/EventHandlers.ts
    events:
      - event: MintComment(address indexed sender, address indexed tokenContract, uint256 indexed tokenId, uint256 quantity, string comment)
        field_selection:
          transaction_fields:
            - hash
networks:
  - id: 8453
    start_block: 0
    contracts:
      - name: ERC20Minter
        address: 0xE27d9Dc88dAB82ACa3ebC49895c663C6a0CfA014

  - id: 84532
    start_block: 0
    contracts:
      - name: ERC20Minter
        address: 0x4538d7a07227d21597fb851a14057f00d15b4d5e

unordered_multichain_mode: true
preload_handlers: true
